### ISSUE TITLE
.gitignore roster

### ISSUE THREAD

**Issue by mhamilt** [kodokoto/juliaDSP#2]
There are a few items that would be worth adding to a `.gitignore`. You'll need to purge these files from the repository after they've been added.

- [x] `externals/` since the externals are the _product_ of the build, they'll change constantly. They are also binary files at their core, so best to not include these. Once you've got a build you're happy with, create a [release](https://github.com/kodokoto/juliaDSP/releases)
- [x] `.DS_Store`, which is a spotlight index file. It doesn't hurt to have it, but it just clutters the place up. 
- [x] `build/build/XCBuildData`

There are probably some more, especially around the actual Xcode projects themselves. Files that are generated by CMake you can largely leave out. At the same time, you can leave the project files there to avoid having other rebuild.

it would be worth looking at other CMake based projects for reference.

**Comment by mhamilt** [comment]
- [x] `build/`: every thing here is generated by CMake. I'd ditch all of these entirely an add some build instructions #4

**Comment by kodokoto** [comment]
Done!
