### ISSUE TITLE
Julia calls in simplemsp_perform64 DSP loop

### ISSUE THREAD

**Issue by mhamilt** [kodokoto/juliaDSP#6]
In your main DSP loop `simplemsp_perform64` you have a few calls that will likely gum up the works

for instance

https://github.com/kodokoto/juliaDSP/blob/e98a777d64096d354a09e8e10e271cc704feba21/source/projects/dspnode%7E/dspnode%7E.c#L110

this will happen on every new audio buffer, which will get very messy, very quickly.

**Comment by kodokoto** [comment]
Yes that line was just there for testing, to see if I commented out the rest of the dsp code and just make julia print something out would still crash Max. 

Thats my bad, I probably should of commented it out or deleted it out right.

**Comment by kodokoto** [comment]
I decided to delete it for clarity
